# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4f574fc0a377713920b9cb1d729cc3839356ebbd9e26b2082af618e5c7c54e715fb22cee5e96b693f72ed39b6e48aaab63fb6991d893d78258474fe6deff248

test:
  secret_key_base: a0dcb443aef0a017bcd2073b513271eb4d23c91ab794abacb94f8dfb9d0c8ff82e07cf6ea7bfd6a94319238336df41d29e918d91504ded0e9f05b2e13dd440c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
